// apps/site/src/components/profile.tsx
import AvatarIcon from './avatar-icon';

export type ProfileProps = {
  avatar: string;
  username: string;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
};

export const Profile = ({ username, avatar, size = 'md' }: ProfileProps) => {
  return (
    <div className="flex items-center gap-2">
      <span className="rounded-full bg-stone-700 p-2 text-stone-100">
        <AvatarIcon avatar={avatar} size={size} />
      </span>
      <span>{username}</span>
    </div>
  );
};

export default Profile;

// apps/chat/src/lib/components/profile.svelte
<script>
  import Avatar from './avatar.svelte';

  /** @type {User} */
  export let user;

  /** @type {'xs' | 'sm' | 'md' | 'lg'} */
  export let size = 'md';

  let avatar = user.avatar;
</script>

<div class="flex items-center gap-2">
  <Avatar {avatar} size="sm" />
  <span
    class:text-xs={size === 'xs'}
    class:text-sm={size === 'sm'}
    class:text-base={size === 'md'}
    class:text-lg={size === 'lg'}>
    {user.username}
  </span>
</div>
